#!/usr/bin/env bash
# Generates the include list that ENRMLibraryTests.mm pulls in, so the
# EnrichedMarkdownExampleTests target picks up every XCTest source under
# packages/react-native-enriched-markdown/__tests__/ios without a project.pbxproj
# edit per file.
#
# Why this exists: EnrichedMarkdownExample.xcodeproj is objectVersion 54 and
# lists sources explicitly, so a new test file would otherwise need a
# PBXFileReference, a PBXBuildFile, a group entry and a Sources-phase entry
# before it ever compiled - and a file nobody wired stayed silently unrun, which
# is exactly how the lane passed while covering nothing. Gradle auto-discovers
# src/test/java on Android; this gives the iOS lane the same property.
#
# The discovered sources are #included into one umbrella translation unit rather
# than compiled separately, because the Sources phase is what we are avoiding
# touching. Consequence: file-scope helpers in these sources share one
# namespace, so name them distinctly (the ENRM prefix already does this for
# classes).
#
# Run as a build phase on the test target (before Sources); DERIVED_FILE_DIR is
# supplied by Xcode. It can also be run by hand with DERIVED_FILE_DIR set.
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "$script_dir/../../.." && pwd)"
tests_dir="$repo_root/packages/react-native-enriched-markdown/__tests__/ios"

if [ -z "${DERIVED_FILE_DIR:-}" ]; then
  echo "DERIVED_FILE_DIR is not set; run this from an Xcode build phase." >&2
  exit 1
fi

out="$DERIVED_FILE_DIR/ENRMGeneratedTestSources.h"
mkdir -p "$DERIVED_FILE_DIR"

count=0
echo "// Generated by scripts/generate-ios-test-sources.sh. Do not edit." >"$out.new"
if [ -d "$tests_dir" ]; then
  while IFS= read -r file; do
    echo "#include \"$file\"" >>"$out.new"
    count=$((count + 1))
  done < <(find "$tests_dir" -maxdepth 1 -type f \( -name '*.m' -o -name '*.mm' \) | sort)
fi

if [ "$count" -eq 0 ]; then
  echo "// No XCTest sources found in $tests_dir." >>"$out.new"
fi

if [ -f "$out" ] && cmp -s "$out" "$out.new"; then
  rm -f "$out.new"
else
  mv "$out.new" "$out"
fi

echo "Wired $count iOS test source(s) from $tests_dir"
